apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-moodle
  labels:
    app: moodle-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/moodle"

